spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: user
    password: user
    pool:
      max-size: 10
      max-create-connection-time: 1000
      max-life-time: 10000

article:
  pageLimit: 100